name: Feature
description: Create an issue for a new feature to implement.
title: "[FEATURE]: "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the feature you want to implement.
      placeholder: "Describe the feature you want to implement."
    validations:
      required: true
  - type: textarea
    attributes:
      label: To do
      description: Describe the steps to implement the feature.
      placeholder: "Describe the steps to implement the feature."
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Priority
      description: Describe the priority of the feature.
      options:
        - Low
        - Medium
        - High
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Project parts
      description: Select the parts of the project that are affected by the feature.
      options:
        - label: Server
        - label: Application
        - label: Web
        - label: Automation
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      placeholder: "Add any other context or screenshots about the feature request here."
    validations:
      required: false