name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  docker-compose-validity:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check existing files
        id: existing-files
        run: .github/scripts/docker-compose-existing-files.sh >> $GITHUB_STEP_SUMMARY
      - name: Check docker-file consistancy
        run: .github/scripts/docker-compose-consistancy.sh >> $GITHUB_STEP_SUMMARY

  count-service-number:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Count service
        run: |
          echo "Number of services: $($(ls -1 ./Server/Services/description | wc -l)-1)" >> $GITHUB_STEP_SUMMARY
      - name: Count action-reaction
        run: |
          .github/scripts/count-action-reaction.sh >> $GITHUB_STEP_SUMMARY

  run-docker-compose:
    needs: ["docker-compose-validity"]
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
      matrix:
        type: ["server", "client_mobile", "client_web"]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Write env file for server
        if: matrix.type == 'server'
        run: echo "${{ secrets.FIREBASE_CONFIG }}" >> ./Server/firebaseConfig.js
      - name: Write env file for application
        if: matrix.type == 'client_mobile'
        run: echo '${{ secrets.MOBILE_APP_ENV_JS }}' > ./Application/env.ts
      - name: Run docker-compose up --build -d -t ${{ matrix.type }}
        run: docker-compose up --build -d -t ${{ matrix.type }}

  mirroring:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: 'run-docker-compose'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ secrets.EPI_REPO_URL }}
          ssh_private_key:
            ${{ secrets.EPI_MIRRORING_KEY }}