name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  pull_request_review:
  workflow_dispatch:

jobs:
  docker-compose-validity:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check existing files
        id: existing-files
        run: .github/scripts/docker-compose-existing-files.sh >> $GITHUB_STEP_SUMMARY
      - name: Check docker-file consistancy
        run: .github/scripts/docker-compose-consistancy.sh >> $GITHUB_STEP_SUMMARY

  run-docker-compose-server:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event_name == 'pull_request_review'
    needs: ["docker-compose-validity"]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run docker-compose build server
        id: run-docker-compose-build-server
        run: docker-compose build server
      - name: Re-request review
        if: failure()
        uses: andrewmusgrave/automatic-pull-request-review@0.0.5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          event: REQUEST_CHANGES
          body: "Run docker-compose build server failed."

  run-docker-compose-client-mobile:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event_name == 'pull_request_review'
    needs: ["docker-compose-validity"]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run docker-compose build client_mobile
        id: run-docker-compose-build-client-mobile
        run: docker-compose build client_mobile
      - name: Re-request review
        if: failure()
        uses: andrewmusgrave/automatic-pull-request-review@0.0.5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          event: REQUEST_CHANGES
          body: "Run docker-compose build client-web failed."

  run-docker-compose-client-web:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event_name == 'pull_request_review'
    needs: ["docker-compose-validity"]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run docker-compose build client_web
        id: run-docker-compose-build-client-web
        run: docker-compose build client_web
      - name: Re-request review
        if: failure()
        uses: andrewmusgrave/automatic-pull-request-review@0.0.5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          event: REQUEST_CHANGES
          body: "Run docker-compose build client-web failed."

  mirroring:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: ["run-docker-compose-server", "run-docker-compose-client-mobile", run-docker-compose-client-web]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ secrets.EPI_REPO_URL }}
          ssh_private_key:
            ${{ secrets.EPI_MIRRORING_KEY }}