name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  docker-compose-validity:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check existing files
        id: existing-files
        run: .github/scripts/docker-compose-existing-files.sh >> $GITHUB_STEP_SUMMARY
      - name: Check docker-file consistancy
        run: .github/scripts/docker-compose-consistancy.sh >> $GITHUB_STEP_SUMMARY

  services-validity:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Count services
        run: |
          .github/scripts/count-services.sh >> $GITHUB_STEP_SUMMARY
      - name: Count actions-reactions
        run: |
          .github/scripts/count-actions-reactions.sh >> $GITHUB_STEP_SUMMARY

  run-docker-compose:
    needs: ["docker-compose-validity"]
    runs-on: ubuntu-22.04
    # steps:
    #   - uses: actions/checkout@v3
    #     with:
    #       fetch-depth: 0
    #   - name: Run docker-compose up --build -d -t 10
    #     run: docker-compose up --build -d -t 10
    strategy:
      fail-fast: true
      matrix:
        type: ["server", "client_mobile", "client_web"]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Write env file for server
        if: matrix.type == 'server'
        run: echo "${{ secrets.ENV_server }}" >> ./Server/firebaseConfig.js
      - name: Write env file for application
        if: matrix.type == 'client_mobile'
        run: echo '${{ secrets.ENV_client_mobile }}' >> ./Application/env.ts
      - name: Write env file for web
        if: matrix.type == 'client_web'
        run: echo '${{ secrets.ENV_client_web }}' >> ./Web/src/firebaseConfig.js
      - name: Run docker-compose up --build -d -t 10 ${{ matrix.type }}
        run: docker-compose up --build -d -t 10 --force-recreate ${{ matrix.type }}

  mirroring:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: 'run-docker-compose'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ secrets.EPI_REPO_URL }}
          ssh_private_key:
            ${{ secrets.EPI_MIRRORING_KEY }}