name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  docker-compose:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Existing files
        run: |
          nbTests=4
          nbSuccess=0
          find docker-compose.yml && let nbSuccess++ || echo "docker-compose.yml not found" >&2
          find Server/Dockerfile && let nbSuccess++ || echo "Server/Dockerfile not found" >&2
          find Web/Dockerfile && let nbSuccess++ || echo "Web/Dockerfile not found" >&2
          find Client/Dockerfile && let nbSuccess++ || echo "Client/Dockerfile not found" >&2
          if (($nbSuccess == nbTests))
          then
            echo "All file ($nbTests) are found!"
          else
            echo "$nbSuccess/$nbTests are found. Check previous line on stdout to know which file is missing."
          fi
          exit $(($nbTests-nbSuccess))

  mirroring:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ secrets.EPI_REPO_URL }}
          ssh_private_key:
            ${{ secrets.EPI_MIRRORING_KEY }}