name: Documentation
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      parts:
        description: Select documentation to generate
        required: true
        type: choice
        options:
          - "server"
          - "web"
          - "all"

jobs:
  server-documentation:
    if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && (github.event.inputs.parts == 'all' || github.event.inputs.parts == 'server'))
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create server documentation
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./Server/
          recurse: true
          output_dir: ./server-docs
          front_page: ./Server/readme.md
      - name: Upload server documentation
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: server-docs
          target-folder: docs/server
  web-documentation:
    if: github.event_name == 'pull_request' || github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && (github.event.inputs.parts == 'all' || github.event.inputs.parts == 'web'))
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create web documentation
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./Web/src
          recurse: true
          output_dir: ./web-docs
          front_page: ./Web/readme.md
      - name: Upload web documentation
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: web-docs
          target-folder: docs/web