name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: cd Web && yarn
    - name: Install Playwright Browsers
      run: cd Web && yarn playwright install --with-deps
    - name: Run Playwright tests
      run: cd Web && echo '${{ secrets.ENV_client_web }}' >> ./src/firebaseConfig.js && (yarn start &) && curl "http://localhost:3000" &&  yarn playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: Web/playwright-report/
        retention-days: 30
