version: "2.2"
services:
  web:
    depends_on:
      mobile:
        condition: service_started
    build:
      context: ./
      dockerfile: Dockerfile
    image: areacontainerregistry.azurecr.io/web
    command: npm start
    ports:
      - "8081:8081"
    volumes:
      - area:/release
    container_name: web

  mobile:
    build:
      context: ../Application
      dockerfile: Dockerfile
    image: areacontainerregistry.azurecr.io/mobile
    volumes:
      - area:/release
    container_name: mobile


volumes:
  area:
    driver: azure_file
    driver_opts:
      share_name: area
      storage_account_name: areastorage2023